// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: MtmcKR1GuwbKEBJfYkVdj
// Component: eW-v92peeoVq

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import Button from "../../Button"; // plasmic-import: 7c1YDuGGoKuq/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: MtmcKR1GuwbKEBJfYkVdj/projectcss
import sty from "./PlasmicOptions.module.css"; // plasmic-import: eW-v92peeoVq/css

import PlusSvgIcon from "./icons/PlasmicIcon__PlusSvg"; // plasmic-import: 8gLchf1ApTDC/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: _VJXnu9sySb9/icon
import TicketSvgIcon from "./icons/PlasmicIcon__TicketSvg"; // plasmic-import: OxvLqJub0eBw/icon
import ChartBarSvgIcon from "./icons/PlasmicIcon__ChartBarSvg"; // plasmic-import: 3t-0dYdjwthe/icon
import GearSvgIcon from "./icons/PlasmicIcon__GearSvg"; // plasmic-import: 4Ujl0fCKxdzC/icon

createPlasmicElementProxy;

export type PlasmicOptions__VariantMembers = {};
export type PlasmicOptions__VariantsArgs = {};
type VariantPropType = keyof PlasmicOptions__VariantsArgs;
export const PlasmicOptions__VariantProps = new Array<VariantPropType>();

export type PlasmicOptions__ArgsType = {};
type ArgPropType = keyof PlasmicOptions__ArgsType;
export const PlasmicOptions__ArgProps = new Array<ArgPropType>();

export type PlasmicOptions__OverridesType = {
  root?: Flex__<"div">;
};

export interface DefaultOptionsProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicOptions__RenderFunc(props: {
  variants: PlasmicOptions__VariantsArgs;
  args: PlasmicOptions__ArgsType;
  overrides: PlasmicOptions__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  return (
    <Stack__
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.root
      )}
    >
      <Button
        className={classNames("__wab_instance", sty.button___1NsP)}
        onClick={async event => {
          const $steps = {};

          $steps["goToCreateEvent"] = true
            ? (() => {
                const actionArgs = { destination: `/create-event` };
                return (({ destination }) => {
                  if (
                    typeof destination === "string" &&
                    destination.startsWith("#")
                  ) {
                    document
                      .getElementById(destination.substr(1))
                      .scrollIntoView({ behavior: "smooth" });
                  } else {
                    __nextRouter?.push(destination);
                  }
                })?.apply(null, [actionArgs]);
              })()
            : undefined;
          if (
            $steps["goToCreateEvent"] != null &&
            typeof $steps["goToCreateEvent"] === "object" &&
            typeof $steps["goToCreateEvent"].then === "function"
          ) {
            $steps["goToCreateEvent"] = await $steps["goToCreateEvent"];
          }
        }}
        startIcon={
          <PlusSvgIcon
            className={classNames(projectcss.all, sty.svg__kwj48)}
            role={"img"}
          />
        }
      >
        {"Create"}
      </Button>
      <Button
        className={classNames("__wab_instance", sty.button__eyw5S)}
        startIcon={
          <TicketSvgIcon
            className={classNames(projectcss.all, sty.svg__pKpEl)}
            role={"img"}
          />
        }
      >
        {"Tickets"}
      </Button>
      <Button
        className={classNames("__wab_instance", sty.button___0PUno)}
        startIcon={
          <ChartBarSvgIcon
            className={classNames(projectcss.all, sty.svg__iVbXu)}
            role={"img"}
          />
        }
      >
        {"Metrics"}
      </Button>
      <Button
        className={classNames("__wab_instance", sty.button__jAe4)}
        startIcon={
          <GearSvgIcon
            className={classNames(projectcss.all, sty.svg__dsPL)}
            role={"img"}
          />
        }
      >
        {"Settings"}
      </Button>
    </Stack__>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicOptions__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicOptions__VariantsArgs;
    args?: PlasmicOptions__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicOptions__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicOptions__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicOptions__ArgProps,
          internalVariantPropNames: PlasmicOptions__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicOptions__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicOptions";
  } else {
    func.displayName = `PlasmicOptions.${nodeName}`;
  }
  return func;
}

export const PlasmicOptions = Object.assign(
  // Top-level PlasmicOptions renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicOptions
    internalVariantProps: PlasmicOptions__VariantProps,
    internalArgProps: PlasmicOptions__ArgProps
  }
);

export default PlasmicOptions;
/* prettier-ignore-end */
