// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicDragAndDropFiles,
  DefaultDragAndDropFilesProps
} from "./plasmic/kollaboration_ghl/PlasmicDragAndDropFiles";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface DragAndDropFilesProps extends Omit<DefaultDragAndDropFilesProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultDragAndDropFilesProps altogether and have
// total control over the props for your component.
export interface DragAndDropFilesProps extends DefaultDragAndDropFilesProps {}

function DragAndDropFiles_(
  props: DragAndDropFilesProps,
  ref: HTMLElementRefOf<"div">
) {
  // Use PlasmicDragAndDropFiles to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicDragAndDropFiles are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all DragAndDropFilesProps here, but feel free
  // to do whatever works for you.

  return <PlasmicDragAndDropFiles root={{ ref }} {...props} />;
}

const DragAndDropFiles = React.forwardRef(DragAndDropFiles_);
export default DragAndDropFiles;
