// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6nkmFbRpkCCeYJxNDNvxHP
// Component: dRisyoJI7K08

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";
import {
  executePlasmicDataOp,
  usePlasmicDataOp,
  usePlasmicInvalidate
} from "@plasmicapp/react-web/lib/data-sources";

import { FormWrapper } from "@plasmicpkgs/antd5/skinny/Form";
import { formHelpers as FormWrapper_Helpers } from "@plasmicpkgs/antd5/skinny/Form";
import { FormItemWrapper } from "@plasmicpkgs/antd5/skinny/FormItem";
import { AntdInput } from "@plasmicpkgs/antd5/skinny/registerInput";
import { inputHelpers as AntdInput_Helpers } from "@plasmicpkgs/antd5/skinny/registerInput";
import { AntdTextArea } from "@plasmicpkgs/antd5/skinny/registerInput";
import { inputHelpers as AntdTextArea_Helpers } from "@plasmicpkgs/antd5/skinny/registerInput";
import { AntdInputNumber } from "@plasmicpkgs/antd5/skinny/registerInput";
import { AntdSwitch } from "@plasmicpkgs/antd5/skinny/registerSwitch";
import DragAndDropUploader from "../../DragAndDropUploader"; // plasmic-import: 6HQmRPP3VFts/component
import TextInput from "../../TextInput"; // plasmic-import: 8UuapZzmVgHc/component
import DragAndDropFiles from "../../DragAndDropFiles"; // plasmic-import: whErWOxtSzQn/component
import { AntdButton } from "@plasmicpkgs/antd5/skinny/registerButton";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 6nkmFbRpkCCeYJxNDNvxHP/projectcss
import sty from "./PlasmicCreateCommunity.module.css"; // plasmic-import: dRisyoJI7K08/css

import CompassSvgIcon from "./icons/PlasmicIcon__CompassSvg"; // plasmic-import: Fmf9646b-oNB/icon
import Plus1SvgIcon from "./icons/PlasmicIcon__Plus1Svg"; // plasmic-import: jeMNj42KSlt-/icon
import SearchSvgIcon from "./icons/PlasmicIcon__SearchSvg"; // plasmic-import: s_pbgKf5r6YF/icon
import CheckSvgIcon from "./icons/PlasmicIcon__CheckSvg"; // plasmic-import: dV_M4gggqVX-/icon

createPlasmicElementProxy;

export type PlasmicCreateCommunity__VariantMembers = {};
export type PlasmicCreateCommunity__VariantsArgs = {};
type VariantPropType = keyof PlasmicCreateCommunity__VariantsArgs;
export const PlasmicCreateCommunity__VariantProps =
  new Array<VariantPropType>();

export type PlasmicCreateCommunity__ArgsType = {};
type ArgPropType = keyof PlasmicCreateCommunity__ArgsType;
export const PlasmicCreateCommunity__ArgProps = new Array<ArgPropType>();

export type PlasmicCreateCommunity__OverridesType = {
  root?: Flex__<"div">;
  section?: Flex__<"section">;
  form?: Flex__<typeof FormWrapper>;
  input?: Flex__<typeof AntdInput>;
  textArea?: Flex__<typeof AntdTextArea>;
  textArea2?: Flex__<typeof AntdTextArea>;
  numberInput?: Flex__<typeof AntdInputNumber>;
  priceSwitch?: Flex__<typeof AntdSwitch>;
  _switch?: Flex__<typeof AntdSwitch>;
  dragAndDropUploader?: Flex__<typeof DragAndDropUploader>;
  textInput?: Flex__<typeof TextInput>;
  dragAndDropFiles?: Flex__<typeof DragAndDropFiles>;
  textInput2?: Flex__<typeof TextInput>;
  button?: Flex__<typeof AntdButton>;
};

export interface DefaultCreateCommunityProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicCreateCommunity__RenderFunc(props: {
  variants: PlasmicCreateCommunity__VariantsArgs;
  args: PlasmicCreateCommunity__ArgsType;
  overrides: PlasmicCreateCommunity__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = useCurrentUser?.() || {};

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "form.value",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "form",
        onMutate: generateOnMutateForSpec("value", FormWrapper_Helpers)
      },
      {
        path: "form.isSubmitting",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false,

        refName: "form",
        onMutate: generateOnMutateForSpec("isSubmitting", FormWrapper_Helpers)
      },
      {
        path: "input.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      },
      {
        path: "textArea.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdTextArea_Helpers)
      },
      {
        path: "textArea2.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdTextArea_Helpers)
      },
      {
        path: "numberInput.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "_switch.checked",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "priceSwitch.checked",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined
      },
      {
        path: "textInput.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ""
      },
      {
        path: "textInput2[].value",
        type: "private",
        variableType: "text"
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });
  const dataSourcesCtx = usePlasmicDataSourceContext();
  const plasmicInvalidate = usePlasmicInvalidate();

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicCreateCommunity.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicCreateCommunity.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicCreateCommunity.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.root
          )}
        >
          <section
            data-plasmic-name={"section"}
            data-plasmic-override={overrides.section}
            className={classNames(projectcss.all, sty.section)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__rBcEe)}>
              <div className={classNames(projectcss.all, sty.freeBox__hsR8N)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__snDKw)}
                  onClick={async event => {
                    const $steps = {};

                    $steps["goToUserDashboard"] = true
                      ? (() => {
                          const actionArgs = { destination: `/user-dashboard` };
                          return (({ destination }) => {
                            if (
                              typeof destination === "string" &&
                              destination.startsWith("#")
                            ) {
                              document
                                .getElementById(destination.substr(1))
                                .scrollIntoView({ behavior: "smooth" });
                            } else {
                              __nextRouter?.push(destination);
                            }
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["goToUserDashboard"] != null &&
                      typeof $steps["goToUserDashboard"] === "object" &&
                      typeof $steps["goToUserDashboard"].then === "function"
                    ) {
                      $steps["goToUserDashboard"] = await $steps[
                        "goToUserDashboard"
                      ];
                    }
                  }}
                >
                  <CompassSvgIcon
                    className={classNames(projectcss.all, sty.svg__j51XA)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zsiaK
                    )}
                  >
                    {"My Communities"}
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__m8QoZ)}
                  onClick={async event => {
                    const $steps = {};

                    $steps["goToCreateCommunity"] = true
                      ? (() => {
                          const actionArgs = { destination: `/` };
                          return (({ destination }) => {
                            if (
                              typeof destination === "string" &&
                              destination.startsWith("#")
                            ) {
                              document
                                .getElementById(destination.substr(1))
                                .scrollIntoView({ behavior: "smooth" });
                            } else {
                              __nextRouter?.push(destination);
                            }
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["goToCreateCommunity"] != null &&
                      typeof $steps["goToCreateCommunity"] === "object" &&
                      typeof $steps["goToCreateCommunity"].then === "function"
                    ) {
                      $steps["goToCreateCommunity"] = await $steps[
                        "goToCreateCommunity"
                      ];
                    }
                  }}
                >
                  <Plus1SvgIcon
                    className={classNames(projectcss.all, sty.svg__hJ8Sw)}
                    role={"img"}
                  />

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__lhBt0
                    )}
                  >
                    {"Create"}
                  </div>
                </Stack__>
              </div>
            </div>
          </section>
          {(() => {
            const child$Props = {
              className: classNames("__wab_instance", sty.form),
              extendedOnValuesChange:
                generateStateOnChangePropForCodeComponents(
                  $state,
                  "value",
                  ["form", "value"],
                  FormWrapper_Helpers
                ),
              formItems: [
                { label: "Name", name: "name", inputType: "Text" },
                { label: "Message", name: "message", inputType: "Text Area" }
              ],
              labelCol: { span: 8, horizontalOnly: true },
              layout: "vertical",
              mode: "advanced",
              onFinish: async values => {
                const $steps = {};

                $steps["httpPost"] = true
                  ? (() => {
                      const actionArgs = {
                        dataOp: {
                          sourceId: "hcB8E47YRDpisPZ3DSKShe",
                          opId: "f0591b1a-07a2-4a3d-b33a-b6dec3f3c638",
                          userArgs: {
                            body: [
                              $state.form.value.Title,
                              $state.form.value.ShortDescription,
                              $state.form.value.Description,
                              $state.form.value.Price,
                              $state.form.value.Active,
                              localStorage.getItem("uploadedFileId"),
                              $state.form.value.Price > 0 ? true : false
                            ]
                          },
                          cacheKey: null,
                          invalidatedKeys: [],
                          roleId: null
                        }
                      };
                      return (async ({ dataOp, continueOnError }) => {
                        try {
                          const response = await executePlasmicDataOp(dataOp, {
                            userAuthToken: dataSourcesCtx?.userAuthToken,
                            user: dataSourcesCtx?.user
                          });
                          await plasmicInvalidate(dataOp.invalidatedKeys);
                          return response;
                        } catch (e) {
                          if (!continueOnError) {
                            throw e;
                          }
                          return e;
                        }
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["httpPost"] != null &&
                  typeof $steps["httpPost"] === "object" &&
                  typeof $steps["httpPost"].then === "function"
                ) {
                  $steps["httpPost"] = await $steps["httpPost"];
                }

                $steps["httpPost2"] = true
                  ? (() => {
                      const actionArgs = {
                        dataOp: {
                          sourceId: "hcB8E47YRDpisPZ3DSKShe",
                          opId: "129c2981-aa19-41a3-9cef-fb6581b9a88e",
                          userArgs: {
                            body: [
                              (() => {
                                const uploadedFileIds = JSON.parse(
                                  localStorage.getItem("uploadedFileIds")
                                );
                                const result = Array.isArray(uploadedFileIds)
                                  ? uploadedFileIds.map(files => ({
                                      Communities_id:
                                        $steps.httpPost.data.response.data.id,
                                      directus_files_id: files
                                    }))
                                  : [];
                                return result;
                              })()
                            ]
                          },
                          cacheKey: null,
                          invalidatedKeys: [],
                          roleId: null
                        }
                      };
                      return (async ({ dataOp, continueOnError }) => {
                        try {
                          const response = await executePlasmicDataOp(dataOp, {
                            userAuthToken: dataSourcesCtx?.userAuthToken,
                            user: dataSourcesCtx?.user
                          });
                          await plasmicInvalidate(dataOp.invalidatedKeys);
                          return response;
                        } catch (e) {
                          if (!continueOnError) {
                            throw e;
                          }
                          return e;
                        }
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["httpPost2"] != null &&
                  typeof $steps["httpPost2"] === "object" &&
                  typeof $steps["httpPost2"].then === "function"
                ) {
                  $steps["httpPost2"] = await $steps["httpPost2"];
                }
              },
              onIsSubmittingChange: generateStateOnChangePropForCodeComponents(
                $state,
                "isSubmitting",
                ["form", "isSubmitting"],
                FormWrapper_Helpers
              ),
              ref: ref => {
                $refs["form"] = ref;
              },
              submitSlot: null,
              wrapperCol: { span: 16, horizontalOnly: true }
            };
            initializeCodeComponentStates(
              $state,
              [
                {
                  name: "value",
                  plasmicStateName: "form.value"
                },
                {
                  name: "isSubmitting",
                  plasmicStateName: "form.isSubmitting"
                }
              ],
              [],
              FormWrapper_Helpers ?? {},
              child$Props
            );

            return (
              <FormWrapper
                data-plasmic-name={"form"}
                data-plasmic-override={overrides.form}
                {...child$Props}
              >
                <FormItemWrapper
                  className={classNames("__wab_instance", sty.formField__oxIv)}
                  initialValue={"title"}
                  label={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__nfD3S
                      )}
                    >
                      {"Title"}
                    </div>
                  }
                  name={"Title"}
                  rules={[{ ruleType: "required" }]}
                >
                  {(() => {
                    const child$Props = {
                      className: classNames("__wab_instance", sty.input),
                      onChange: generateStateOnChangePropForCodeComponents(
                        $state,
                        "value",
                        ["input", "value"],
                        AntdInput_Helpers
                      ),
                      value: generateStateValueProp($state, ["input", "value"])
                    };
                    initializeCodeComponentStates(
                      $state,
                      [
                        {
                          name: "value",
                          plasmicStateName: "input.value"
                        }
                      ],
                      [],
                      AntdInput_Helpers ?? {},
                      child$Props
                    );

                    return (
                      <AntdInput
                        data-plasmic-name={"input"}
                        data-plasmic-override={overrides.input}
                        {...child$Props}
                      />
                    );
                  })()}
                </FormItemWrapper>
                <FormItemWrapper
                  className={classNames("__wab_instance", sty.formField__naScx)}
                  label={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__eq4Qp
                      )}
                    >
                      {"Short Description"}
                    </div>
                  }
                  name={"ShortDescription"}
                  rules={[{ ruleType: "required" }]}
                >
                  {(() => {
                    const child$Props = {
                      className: classNames("__wab_instance", sty.textArea),
                      onChange: generateStateOnChangePropForCodeComponents(
                        $state,
                        "value",
                        ["textArea", "value"],
                        AntdTextArea_Helpers
                      ),
                      value: generateStateValueProp($state, [
                        "textArea",
                        "value"
                      ])
                    };
                    initializeCodeComponentStates(
                      $state,
                      [
                        {
                          name: "value",
                          plasmicStateName: "textArea.value"
                        }
                      ],
                      [],
                      AntdTextArea_Helpers ?? {},
                      child$Props
                    );

                    return (
                      <AntdTextArea
                        data-plasmic-name={"textArea"}
                        data-plasmic-override={overrides.textArea}
                        {...child$Props}
                      />
                    );
                  })()}
                </FormItemWrapper>
                <FormItemWrapper
                  className={classNames("__wab_instance", sty.formField__c0Jy9)}
                  label={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__oBpU
                      )}
                    >
                      {"Description"}
                    </div>
                  }
                  name={"Description"}
                  rules={[{ ruleType: "required" }]}
                >
                  {(() => {
                    const child$Props = {
                      className: classNames("__wab_instance", sty.textArea2),
                      onChange: generateStateOnChangePropForCodeComponents(
                        $state,
                        "value",
                        ["textArea2", "value"],
                        AntdTextArea_Helpers
                      ),
                      value: generateStateValueProp($state, [
                        "textArea2",
                        "value"
                      ])
                    };
                    initializeCodeComponentStates(
                      $state,
                      [
                        {
                          name: "value",
                          plasmicStateName: "textArea2.value"
                        }
                      ],
                      [],
                      AntdTextArea_Helpers ?? {},
                      child$Props
                    );

                    return (
                      <AntdTextArea
                        data-plasmic-name={"textArea2"}
                        data-plasmic-override={overrides.textArea2}
                        {...child$Props}
                      />
                    );
                  })()}
                </FormItemWrapper>
                <FormItemWrapper
                  className={classNames("__wab_instance", sty.formField__a4EdM)}
                  label={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__jf88M
                      )}
                    >
                      {"Price"}
                    </div>
                  }
                  name={"Price"}
                  rules={[{ ruleType: "required" }]}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox___6Ib1F)}
                  >
                    <AntdInputNumber
                      data-plasmic-name={"numberInput"}
                      data-plasmic-override={overrides.numberInput}
                      className={classNames("__wab_instance", sty.numberInput)}
                      disabled={(() => {
                        try {
                          return $state.priceSwitch.checked;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return undefined;
                          }
                          throw e;
                        }
                      })()}
                      onChange={generateStateOnChangeProp($state, [
                        "numberInput",
                        "value"
                      ])}
                      type={"number"}
                      value={generateStateValueProp($state, [
                        "numberInput",
                        "value"
                      ])}
                    />

                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__nfgYb)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__wfhry
                        )}
                      >
                        {"Free?"}
                      </div>
                      <AntdSwitch
                        data-plasmic-name={"priceSwitch"}
                        data-plasmic-override={overrides.priceSwitch}
                        checked={generateStateValueProp($state, [
                          "priceSwitch",
                          "checked"
                        ])}
                        className={classNames(
                          "__wab_instance",
                          sty.priceSwitch
                        )}
                        onChange={generateStateOnChangeProp($state, [
                          "priceSwitch",
                          "checked"
                        ])}
                      />
                    </Stack__>
                  </Stack__>
                </FormItemWrapper>
                <FormItemWrapper
                  className={classNames("__wab_instance", sty.formField__avgm3)}
                  label={
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__f3Y8Y
                      )}
                    >
                      {"Active"}
                    </div>
                  }
                  name={"Active"}
                  rules={[{ ruleType: "required" }]}
                >
                  <AntdSwitch
                    data-plasmic-name={"_switch"}
                    data-plasmic-override={overrides._switch}
                    checked={generateStateValueProp($state, [
                      "_switch",
                      "checked"
                    ])}
                    className={classNames("__wab_instance", sty._switch)}
                    onChange={generateStateOnChangeProp($state, [
                      "_switch",
                      "checked"
                    ])}
                  />
                </FormItemWrapper>
                <div className={classNames(projectcss.all, sty.freeBox__qd3Ul)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__mr2G1)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"100%"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={"lazy"}
                    src={(() => {
                      try {
                        return (
                          "https://kollaberation-directus.xc9xgr.easypanel.host/assets/" +
                          localStorage.getItem("uploadedFileId")
                        );
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return undefined;
                        }
                        throw e;
                      }
                    })()}
                  />
                </div>
                <DragAndDropUploader
                  data-plasmic-name={"dragAndDropUploader"}
                  data-plasmic-override={overrides.dragAndDropUploader}
                  className={classNames(
                    "__wab_instance",
                    sty.dragAndDropUploader
                  )}
                  maxFiles={1}
                />

                <TextInput
                  data-plasmic-name={"textInput"}
                  data-plasmic-override={overrides.textInput}
                  className={classNames("__wab_instance", sty.textInput)}
                  onChange={(...eventArgs) => {
                    generateStateOnChangeProp($state, ["textInput", "value"])(
                      (e => e.target?.value).apply(null, eventArgs)
                    );
                  }}
                  value={
                    generateStateValueProp($state, ["textInput", "value"]) ?? ""
                  }
                />

                <div className={classNames(projectcss.all, sty.freeBox__lymeb)}>
                  {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
                    (() => {
                      try {
                        return JSON.parse(
                          localStorage.getItem("uploadedFileIds")
                        );
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return [];
                        }
                        throw e;
                      }
                    })()
                  ).map((__plasmic_item_0, __plasmic_idx_0) => {
                    const currentItem = __plasmic_item_0;
                    const currentIndex = __plasmic_idx_0;
                    return (
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__iJb4
                        )}
                        key={currentIndex}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img__dzqeb)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"auto"}
                          loading={"lazy"}
                          src={(() => {
                            try {
                              return (
                                "https://kollaberation-directus.xc9xgr.easypanel.host/assets/" +
                                currentItem
                              );
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()}
                        />
                      </div>
                    );
                  })}
                </div>
                <DragAndDropFiles
                  data-plasmic-name={"dragAndDropFiles"}
                  data-plasmic-override={overrides.dragAndDropFiles}
                  className={classNames("__wab_instance", sty.dragAndDropFiles)}
                />

                {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
                  (() => {
                    try {
                      return JSON.parse(
                        localStorage.getItem("uploadedFileIds")
                      );
                    } catch (e) {
                      if (
                        e instanceof TypeError ||
                        e?.plasmicType === "PlasmicUndefinedDataError"
                      ) {
                        return [];
                      }
                      throw e;
                    }
                  })()
                ).map((__plasmic_item_0, __plasmic_idx_0) => {
                  const currentItem = __plasmic_item_0;
                  const currentIndex = __plasmic_idx_0;
                  return (() => {
                    const child$Props = {
                      className: classNames("__wab_instance", sty.textInput2),
                      key: currentIndex,
                      onChange: (...eventArgs) => {
                        generateStateOnChangeProp($state, [
                          "textInput2",
                          __plasmic_idx_0,
                          "value"
                        ])((e => e.target?.value).apply(null, eventArgs));
                      },
                      value:
                        generateStateValueProp($state, [
                          "textInput2",
                          __plasmic_idx_0,
                          "value"
                        ]) ?? ""
                    };

                    initializePlasmicStates(
                      $state,
                      [
                        {
                          name: "textInput2[].value",
                          initFunc: ({ $props, $state, $queries }) =>
                            (() => {
                              try {
                                return currentItem;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return undefined;
                                }
                                throw e;
                              }
                            })()
                        }
                      ],
                      [__plasmic_idx_0]
                    );
                    return (
                      <TextInput
                        data-plasmic-name={"textInput2"}
                        data-plasmic-override={overrides.textInput2}
                        {...child$Props}
                      />
                    );
                  })();
                })}
                <AntdButton
                  data-plasmic-name={"button"}
                  data-plasmic-override={overrides.button}
                  className={classNames("__wab_instance", sty.button)}
                  submitsForm={true}
                  type={"primary"}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__yJcdj
                    )}
                  >
                    {"Submit"}
                  </div>
                </AntdButton>
              </FormWrapper>
            );
          })()}
          <div className={classNames(projectcss.all, sty.freeBox__wMvAo)}>
            {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
              (() => {
                try {
                  return JSON.parse(localStorage.getItem("uploadedFileIds"));
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return [];
                  }
                  throw e;
                }
              })()
            ).map((__plasmic_item_0, __plasmic_idx_0) => {
              const currentItem = __plasmic_item_0;
              const currentIndex = __plasmic_idx_0;
              return (
                <div
                  className={classNames(projectcss.all, sty.freeBox__yCj1K)}
                  key={currentIndex}
                />
              );
            })}
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "section",
    "form",
    "input",
    "textArea",
    "textArea2",
    "numberInput",
    "priceSwitch",
    "_switch",
    "dragAndDropUploader",
    "textInput",
    "dragAndDropFiles",
    "textInput2",
    "button"
  ],
  section: ["section"],
  form: [
    "form",
    "input",
    "textArea",
    "textArea2",
    "numberInput",
    "priceSwitch",
    "_switch",
    "dragAndDropUploader",
    "textInput",
    "dragAndDropFiles",
    "textInput2",
    "button"
  ],
  input: ["input"],
  textArea: ["textArea"],
  textArea2: ["textArea2"],
  numberInput: ["numberInput"],
  priceSwitch: ["priceSwitch"],
  _switch: ["_switch"],
  dragAndDropUploader: ["dragAndDropUploader"],
  textInput: ["textInput"],
  dragAndDropFiles: ["dragAndDropFiles"],
  textInput2: ["textInput2"],
  button: ["button"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  section: "section";
  form: typeof FormWrapper;
  input: typeof AntdInput;
  textArea: typeof AntdTextArea;
  textArea2: typeof AntdTextArea;
  numberInput: typeof AntdInputNumber;
  priceSwitch: typeof AntdSwitch;
  _switch: typeof AntdSwitch;
  dragAndDropUploader: typeof DragAndDropUploader;
  textInput: typeof TextInput;
  dragAndDropFiles: typeof DragAndDropFiles;
  textInput2: typeof TextInput;
  button: typeof AntdButton;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCreateCommunity__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCreateCommunity__VariantsArgs;
    args?: PlasmicCreateCommunity__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicCreateCommunity__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicCreateCommunity__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCreateCommunity__ArgProps,
          internalVariantPropNames: PlasmicCreateCommunity__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCreateCommunity__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCreateCommunity";
  } else {
    func.displayName = `PlasmicCreateCommunity.${nodeName}`;
  }
  return func;
}

export const PlasmicCreateCommunity = Object.assign(
  // Top-level PlasmicCreateCommunity renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    section: makeNodeComponent("section"),
    form: makeNodeComponent("form"),
    input: makeNodeComponent("input"),
    textArea: makeNodeComponent("textArea"),
    textArea2: makeNodeComponent("textArea2"),
    numberInput: makeNodeComponent("numberInput"),
    priceSwitch: makeNodeComponent("priceSwitch"),
    _switch: makeNodeComponent("_switch"),
    dragAndDropUploader: makeNodeComponent("dragAndDropUploader"),
    textInput: makeNodeComponent("textInput"),
    dragAndDropFiles: makeNodeComponent("dragAndDropFiles"),
    textInput2: makeNodeComponent("textInput2"),
    button: makeNodeComponent("button"),

    // Metadata about props expected for PlasmicCreateCommunity
    internalVariantProps: PlasmicCreateCommunity__VariantProps,
    internalArgProps: PlasmicCreateCommunity__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Create community",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicCreateCommunity;
/* prettier-ignore-end */
